pwm_frequency: 50

servo_config:
  - {servo: 1, center: 331, direction: -1, range: 106}
  - {servo: 2, center: 334, direction:  1, range: 108}
  - {servo: 3, center: 338, direction: -1, range: 108}
  - {servo: 4, center: 337, direction:  1, range: 108}

drive_config:
  mode: mecanum
  radius: 0.062
  rpm: 60.0
  scale: 0.35
  track: 0.2
  servos:
    - {servo: 1, position: 1}
    - {servo: 2, position: 2}
    - {servo: 3, position: 3}
    - {servo: 4, position: 4}
